version: "3.8"


services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
  cloudVendorAPI:
    image: cloud_api:v1
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - mongodb

